### ISSUE TITLE
realtime stock price, is it necessary?

### ISSUE THREAD

**Issue by doncat99** [Finance-And-ML/US-Stock-Prediction-Using-ML-And-Spark#1]
Here is a suggestion:

1. News released before stock market open, go match the coming "open" price.
2. News released around stock trading time,  go match the coming "close" price.

think it over.

**Comment by Netjimmy** [comment]
Hi @doncat99 ,
Thanks for your suggestion. We refer to this [paper](http://www.sciencedirect.com/science/article/pii/S0167923612000875) 
It tracks the trend of certain stock price after 15 min the stock related article was released.
Of course, we may also attempt to answer the questions you propose.

**Comment by lizichen** [comment]
@doncat99 Yes, there are news released before and after the trading hours, which we streamed all of them nonetheless. I don't quite understand what your language by saying _'go match the coming "open"/"close" price'_, are you referring to the **'opening price'** of a trading day? I'm sure our draft paper has mentioned that we have all intra-day stock prices, which will surely have the open, close, max, min, volume data; just like what you can see from Google Finance and Yahoo Finance charts. Please elaborate your suggestion if I misunderstand this. As of the question _'Is it necessary to have real-time stock data'_, please first refer to @Netjimmy 's answer above. Due to the fact that the influence from public media may apply in a period of time; say 15 minutes or 1 day we compute the trend by looking for the prices at 15 minutes, 1 hour, 2 hours or even further. We run the program with many different parameters (from 15 minutes to 6.5 hours or even further) so as to see an improved accuracy in prediction. Therefore, to answer your question, we do need this **real-time**, **intra-day**, **minute-level**, stock price data set, because apart from several previous researches that have shown some potentials in this approach, no one has ever managed to demonstrate the differences from various combinations of data parameters. Thank you for your question.

**Comment by doncat99** [comment]
@lizichen, @Netjimmy  Hi friends, what I had mentioned above is exactly the "open/close price". There is a saying that the "close price" of a stock is the compromise of all information received today. I am not saying that the "realtime article-price matching" will not provide a better accuracy, but such matching approach may thus bringing lots of noise as well. 
1. Is the article-price correctly matching (timing issue)?
2. Is the article content reflect to the price change?
3. How if the same(similar) articles reflect to a reverse price change? (one 10% raise, the other -10% drop). This will happen when the stock earning report is just declared. Reading and Understanding earning report do take times, but the market doesn't wait. 

Below is a shortcut project for most of all the data you required, though is not implemented var Spark. I am also interested in NLP processing as well, look forward to your outcomes.
https://github.com/doncat99/StockRecommendSystem

**Comment by lizichen** [comment]
@doncat99 Yes, I do think that the close price of a trade day is special, that is also one of the reasons we think we do not want to just have that solo number for a whole day. News starts the day earlier than the market opens; information pours along the 6.5 hours, we want to get something not overly simplified out of it. Our approach is not perfect yet and have some foreseeable limitations and extra effort to make, but the experiment is still undergoing. As for your questions: 1) Yes, all news are retrieved based on their published time attribute, which shows multiple times in a raw html file, meta tag, json text, and third-party toggle tags. And all these time are converted to EST time zone. Stock price data is in EST, too. 2) We don't know this yet, but we assume that news that has a proper sentiment weights throttle passed will have some influence. We match the subject to stock trend for model construction. 3) Correct, opinions are always various, that's why we have to collect large dataset. At certain time or certain occasion; stock market may reflect faster or slower. Our referred paper gives an average time frame, 15 minutes. We are going to try a few more different numbers. We will certainly look into your repository. Thanks for the questions and interest.
